version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - web-root:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - node-app
      - node-app-notifications
  certbot:
    image: certbot/certbot:arm32v6-latest
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email nicolasdeheza@hotmail.com --agree-tos --no-eff-email --force-renewal -d happyday.nicolasdeheza.com
  node-app:
    build:
      context: ./server
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - SECRET=${SECRET}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY}
      - PRIVATE_VAPID_KEY=${PRIVATE_VAPID_KEY}
      - PORT=4000
      - NOTIFICATION=dontSend
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - mongo
  node-app-notifications:
    build:
      context: ./server
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - SECRET=${SECRET}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY}
      - PRIVATE_VAPID_KEY=${PRIVATE_VAPID_KEY}
      - PORT=4001
      - NOTIFICATION=send
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - mongoDb:/data/db
volumes:
  mongoDb:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/happy-day/client/build/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/happy-day/dhparam/
      o: bind
networks:
  app-network:
    driver: bridge
